[Editor]
BorderlessWindow = true
Width = 800
Height = 600
FontFamily = "Source Code Pro for Powerline"
FontSize = 14
Linespace = 6

ExtCmdline   = false
ExtPopupmenu = false
ExtTabline   = false
ExtMessages  = false

Clipboard = true

Macmeta = false

Transparent = 1.0

DrawWindowSeparator = false

## Draw built-in indent guide
IndentGuide = false

DiffAddPattern    = 1
DiffDeletePattern = 1
DiffChangePattern = 1

ClickEffect = false

GinitVim = '''
  " disable geoneovim ui
  augroup GonvimAu
    autocmd!
  augroup end
  augroup GonvimAuStatusline
    autocmd!
  augroup end
  augroup GonvimAuLint
    autocmd!
  augroup end
  augroup GonvimAuMd
    autocmd!
  augroup end
  augroup GonvimAuFilePath
    autocmd!
  augroup end
  augroup GonvimAuMinimap
    autocmd!
  augroup end
  augroup GonvimAuScrollbar
    autocmd!
  augroup end

  " workspace (directory) management
  :nnoremap <silent><Leader>dn :GonvimWorkspaceNew<CR>
  :nnoremap <silent><Leader>dh :GonvimWorkspaceNext<CR>
  :nnoremap <silent><Leader>dl :GonvimWorkspacePrevious<CR>
'''

[Palette]
AreaRatio = 0.5
MaxNumberOfResultItems = 30
Transparent = 1.0

[Message]
Transparent = 1.0

[Statusline]
Visible = false

[Tabline]
Visible = false

[Popupmenu]
ShowDetail = false

[Lint]
Visible = false

[Markdown]
Disable = false

[MiniMap]
Disable = true

[ScrollBar]
Visible = false

[SideBar]
Visible = false

[Workspace]
RestoreSession = false

[FileExplore]
MaxDisplayItems = 30
