[Editor]
BorderlessWindow = false

FontFamily = "Source Code Pro for Powerline"
FontSize = 14

GinitVim = '''
  set guifont=Source\ Code\ Pro\ for\ Powerline:h14

  " goneovim {{{
  nnoremap <silent><C-g>n :execute 'GonvimWorkspaceNew'<CR>
  nnoremap <silent><C-g>h :execute 'GonvimWorkspacePrevious'<CR>
  nnoremap <silent><C-g>l :execute 'GonvimWorkspaceNext'<CR>
  nnoremap <silent><C-g>b :call GonvimWorkspaceBind()<CR>
  nnoremap <silent><C-g>f :execute 'GonvimFuzzyFiles'<CR>
  nnoremap <silent><Leader>q :execute 'GonvimFuzzyAg'<CR>
  " }}}

  " marv {{{
  nnoremap <silent><Leader>h :execute 'MarvHTML'<CR>
  nnoremap <silent><Leader>p :execute 'MarvPDF'<CR>
  " }}}
'''

[MiniMap]
Disable = false

## Specifies whether to show the minimap or not.
# Visible = true

## Specifies the width of the minimap.
# Width = 100


[Markdown]
Disable = true

[SideBar]
Visible = false

# [FileExplore]
## Specify the maximum number of items to be displayed in the file explorer.
# MaxDisplayItems = 30

# [Workspace]
## This setting sets the format of the path string of CWD in the sidebar.
##  name: directoryname
##  full: /path/to/directoryname
##  minimum: /p/t/directoryname
# PathStyle = "minimum"
