#!/bin/bash

TOUCHPAD_ENABLED=$(xinput --list-props 'SynPS/2 Synaptics TouchPad' | awk '/Device Enabled/{print $NF}')
TOUCHPAD='SynPS/2 Synaptics TouchPad'
TOUCHSCREEN='Atmel Atmel maXTouch Digitizer'
TRANSFORM='Coordinate Transformation Matrix'

if [ $TOUCHPAD_ENABLED == 1 ]
then
    xrandr -o inverted
    xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
    xinput disable "$TOUCHPAD"
else
    xrandr -o normal
    xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
    xinput enable "$TOUCHPAD"
fi
