#!/bin/bash

TOUCHPAD_ENABLED=$(xinput --list-props 'SynPS/2 Synaptics TouchPad' | awk '/Device Enabled/{print $NF}')
TOUCHPAD='SynPS/2 Synaptics TouchPad'
TOUCHSCREEN='Atmel Atmel maXTouch Digitizer'
TRANSFORM='Coordinate Transformation Matrix'

# NOTE: In some kernel versions, the screen will go black when
#       xrandr goes directly from normal orientation to inverted
#       orientation. To work around this, go to left orientation
#       first, then go to inverted orientation. YMMV - it may be
#       worth testing against your current kernel to see if the
#       workaround is necessary, but be advised it may require a
#       reboot if the screen goes black.
if [ $TOUCHPAD_ENABLED == 1 ]
then
    xrandr -o left && xrandr -o inverted
    xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
    xinput disable "$TOUCHPAD"
else
    xrandr -o left && xrandr -o normal
    xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
    xinput enable "$TOUCHPAD"
fi
