# GPG Key ID.
export GPGKEY=68DF5757

# rbenv setup.
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# nvm setup.
export NVM_DIR="/home/ratmav/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Make pesonal scripts available in $PATH.
export PATH="$HOME/Scripts:$PATH"

# Run Ansible from source.
source /home/ratmav/Tools/Source\ Builds/ansible/hacking/env-setup -q

# Ansible config.
export ANSIBLE_CONFIG="$HOME/Projects/dotfiles/ansible/ansible.cfg"
export ANSIBLE_INVENTORY="$HOME/Tools/ansible_hosts"
